export const SET_USER = 'SET_USER';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_DASHBOARD_REPORT_TABLE = 'SET_REPORT_TABLE';
export const SET_INSTITUTIONS_TABLE = 'SET_INSTITUTIONS_TABLE';
export const SET_MY_REPORTS_TABLE = 'SET_MY_REPORTS_TABLE';
export const SET_REPORTS_TABLE = 'SET_REPORTS_TABLE';
export const SET_MY_AGENCIES_TABLE = 'SET_MY_AGENCIES_TABLE';

